variable "project_id" {
  type        = string
  description = "GCP project ID used for project-scoped IAM grants."
}

variable "region" {
  type        = string
  description = "GCP region hosting the artifact registry repository."
}

variable "app_name" {
  type        = string
  description = "Human-readable app name. Used in service account display names and as the image path segment in the repository URL."
}

variable "block_ref" {
  type        = string
  description = "Short app reference used as the base for service account account_ids. Truncated per-role to fit the 30-char SA limit."
}

variable "resource_suffix" {
  type        = string
  description = "Random suffix appended to resource names for uniqueness. Generated by the caller (typically a 5-char random_string)."
}

variable "repo_labels" {
  type        = map(string)
  description = "Labels applied to the artifact registry repository."
  default     = {}
}

variable "op_impersonater_emails" {
  type        = list(string)
  description = "Emails of service accounts allowed to impersonate the scaffolding SAs (image pusher, deployer, log reader). Each is granted iam.serviceAccountTokenCreator on every scaffolding SA."
}
